# Install vim plugins

echo Installing Pathogen...
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

echo Installing snipMate...
git clone https://github.com/msanders/snipmate.vim ~/.vim/bundle/snipmate

echo Installing NERD Commenter...
git clone https://github.com/scrooloose/nerdcommenter.git ~/.vim/bundle/nerdcommenter

echo Installing matchit...
git clone https://github.com/vim-scripts/matchit.zip ~/.vim/bundle/matchit

echo Installing fugitive...
git clone git://github.com/tpope/vim-fugitive.git ~/.vim/bundle/vim-fugitive

echo Installing vim-flake8...
git clone https://github.com/nvie/vim-flake8.git ~/.vim/bundle/vim-flake8

echo Installing gitgutter...
git clone git://github.com/airblade/vim-gitgutter.git ~/.vim/bundle/vim-gitgutter.git
